package org.hybridai.refund.calculator;

import org.hybridai.refund.model.*;

rule "Refund eligibility" when
	Flight( $delay : delayInMinutes >= 60 )
then
	insert(new RefundAmount( 2 * $delay )
	        .addExplanation("You're entitled of $2 of refund for each of the " + $delay + " minutes of delay."));
end

rule "Increase refund of 10% for seniors" when
	Customer( age > 65 )
	$r: RefundAmount()
then
    $r.addExplanation("Since you're a senior customer (older than 65) you're also entitled of a 10% increase on your refund.");
	$r.setAmount( $r.getAmount() * 1.1 );
end