package org.hybridai.refund.calculator;

import org.hybridai.refund.model.*;

rule "Eligible for refund if the delay was more than 1 hour" when
	Flight( $delay : delayInMinutes >= 60 )
then
	insert(new RefundAmount());
end

rule "Refund amount is $2 per minute of delay" when
	Flight( $delay : delayInMinutes )
	$r: RefundAmount( amount == 0.0 )
then
	modify($r) { setAmount( 2 * $delay ); }
end

rule "Refund is increased by 10% for seniors (people older than 65)" when
	Customer( age > 65 )
	$r: RefundAmount( amount > 0.0 )
then
	$r.setAmount( $r.getAmount() * 1.1 );
end