package org.hybridai.refund.statemachine;

import org.hybridai.refund.model.*;

rule "Missing Customer" when
	SessionData( customer == null )
then
	insert(ChatState.EXTRACT_CUSTOMER);
end

rule "Missing Flight" when
	SessionData( customer != null, flight == null )
then
	insert(ChatState.EXTRACT_FLIGHT);
end

rule "All Data" when
	SessionData( customer != null, flight != null )
then
	insert(ChatState.CALCULATE_REFUND);
end
