package org.hybridai.password;

rule "Password must contain a special character" when
    $s: String( !this.matches(".*[\\W_].*") )
then
    System.out.println("No special char in " + $s);
    delete($s);
    if ($s.contains("e")) {
        $s = $s.replace('e', '&');
    } else if ($s.contains("a")) {
        $s = $s.replace('a', '@');
    } else if ($s.contains("i")) {
        $s = $s.replace('i', '!');
    } else {
        $s = "#" + $s;
    }
    insert($s);
end

rule "Password must contain a digit" when
    $s: String( !this.matches(".*\\d.*") )
then
    System.out.println("No digit in " + $s);
    delete($s);
    if ($s.contains("e")) {
        $s = $s.replace('e', '3');
    } else if ($s.contains("o")) {
        $s = $s.replace('o', '0');
    } else if ($s.contains("i")) {
        $s = $s.replace('i', '1');
    } else {
        $s = new java.util.Random().nextInt(0,9) + $s;
    }
    insert($s);
end

rule "Password should not contain spaces" when
    $s: String( this.contains(" ") )
then
    System.out.println("Found spaces " + $s);
    delete($s);
    insert($s.replace(' ', '_'));
end

rule "Password must be 10 characters at most" when
    $s: String( length > 8 )
then
    System.out.println("Too long " + $s);
    delete($s);
    insert($s.substring(0,8));
end

rule "Password must be 10 characters at least" when
    $s: String( length < 8 )
then
    System.out.println("Too short " + $s);
    delete($s);
    insert($s + new java.util.Random().nextInt(0,9));
end